name: Build Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Loom Dependencies
        run: sh gradlew dependencies --no-daemon
        working-directory: './swing-speed-template-26.3'
        continue-on-error: true

      - name: Build with Gradle
        run: sh gradlew build --no-daemon
        working-directory: './swing-speed-template-26.3'

      - name: Upload Finished Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: swingspeed-26.3-jar
          path: '**/build/libs/*.jar'
